-- Subscription links: generated by super_admin for companies to sign a plan
create table if not exists public.subscription_links (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  plan text not null,
  plan_name text not null,
  plan_price text not null,
  token text not null unique default encode(gen_random_bytes(24), 'hex'),
  status text not null default 'pending' check (status in ('pending','accepted','expired')),
  created_by uuid references auth.users(id),
  signed_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days')
);

-- Index for fast token lookup
create index if not exists idx_subscription_links_token on public.subscription_links(token);

-- RLS
alter table public.subscription_links enable row level security;

-- Super admins can do anything
create policy "super_admin_all" on public.subscription_links
  for all
  using (
    exists (
      select 1 from public.user_roles
      where user_roles.user_id = auth.uid()
        and user_roles.role = 'super_admin'
    )
  );

-- Anyone can read by token (public page needs to fetch link details)
create policy "public_read_by_token" on public.subscription_links
  for select
  using (true);

-- Anyone authenticated can update status to accepted (company signing)
create policy "sign_subscription" on public.subscription_links
  for update
  using (status = 'pending' and expires_at > now())
  with check (status = 'accepted');
