// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhfpjtswcsotfdssgxsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoZnBqdHN3Y3NvdGZkc3NneHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNzE5MTUsImV4cCI6MjA4OTg0NzkxNX0.TaJ22mSYjCIUZo8dv0xGPf8rRQ5On1_fok8HP66UmfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});